name: critterpedia
version: 1.0.0+2
description: A tool to track fish and bugs in ACNH
publish_to: none

dependencies:
  cached_network_image: ^2.2.0+1
  cupertino_icons: ^0.1.3
  fluro: ^1.6.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.1
  intl: ^0.16.1
  json_annotation: ^3.0.1
  logging: ^0.11.4
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3
  url_launcher: ^5.5.0

dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  pedantic: ^1.9.0
  test: ^1.14.0
  lint: ^1.2.0
  flutter_launcher_icons: ^0.7.5

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CritterIcons
      fonts:
        - asset: fonts/critter_icons/CritterIcons.ttf

flutter_intl:
  enabled: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/launcher/icon_ios.png
  image_path_android: assets/launcher/icon_android.png
  adaptive_icon_background: assets/launcher/background.png
  adaptive_icon_foreground: assets/launcher/foreground.png
