name: critterpedia
description: A tool to track fish and bugs in ACNH
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fluro: ^1.6.3
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3
  logging: ^0.11.4
  json_annotation: ^3.0.1
dev_dependencies:
  test: ^1.14.0
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family:  CritterIcons
      fonts:
        - asset: fonts/critter_icons/CritterIcons.ttf
flutter_intl:
  enabled: true
