/// Flutter icons CritterIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CritterIcons
///      fonts:
///       - asset: fonts/CritterIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CritterIcons {
  CritterIcons._();

  static const _kFontFam = 'CritterIcons';
  static const _kFontPkg = null;

  static const IconData insect = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sea = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
